### PR TITLE
Development

### PR DESCRIPTION
**Pull request by JelilFaisalAbudu**
# Checking for linter errors.
# Request for Bootstrap Project Code Review.

### CODE REVIEW

**Comment by JelilFaisalAbudu** [comment]
# Request for Bootstrap Project Code Review.

- Following the Microverse's general requirements and The Odin Project specifications,  I have completed this project and therefore submitting it for TSE review.

- The specifications on which the project was built are as follows:
# Microverse Project Requirements #
- Setting up Code Linter on the Repo.
- Using Bootstrap CSS classes wherever it is possible.
- Double-check that the page layout does not break on smaller screens.
- Validating the HTML code.

# The Odin Project Requirements #
- Resizing the browser to mimics the behavior of the real Newsweek homepage.

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @JelilFaisalAbudu 
### You have done a great job so far :clap: however, you have a few issues to solve before the project could be approved.
- Remove the space between the navigation and the header, it is one thing
no space
- Also, remove the space below more stories 
remove space
- The height on in the magazine section almost have the same height
almost same equal height
- In the footer, subscribe section the background does not match the design, add padding 
padding
- Add a border to the newsletter section
border
### Make these changes and resubmit for another code review. Good luck.
- Contact me on slack for more clarity @iamraymond
- Happy coding!

**Comment by JelilFaisalAbudu** [comment]
# Request for Review Per The Changes Required By  TSE Earlier Code Reviews And Feedback#
     
   > Remove the space between the navigation and the header, it is one thing.
   - Fixed

  > Also, remove the space below more stories
  - Fixed  

  > The height on in the magazine section almost have the same height.
  - Fixed

  > Add a border to the newsletter section
  - Fixed

**Comment by christianotieno** [comment]
## Pull Request under review by Christian Otieno (TSE)

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @JelilFaisalAbudu  :wave:
-
You have done a good job implementing the requested changes. Keep it up.
We, however, do have some few more changes to carry out before we proceed (see review comment).
##
## [REQUIRED] - FIX - The general width of the page.
- The contents of the main page are not as properly centred as they ought to be.  Everything looks large and spread out. Since we are using bootstrap,  the `container` class could come in handy here in order to achieve the required results.
- This is what we have currently: 👇 
newsweek-clone
- This is what we should be aiming for: 👇 
newswek
- A more compact view with everything well-centred side the main container division ([link to page](https://www.newsweek.com/)).

## [REUIRED] - FIX - The in the magazine section.
- Currently, the two articles on the left-most side in this section are smaller in height than the div of six main articles in the right. They should be slightly taller ([link to page](https://www.newsweek.com/)). Kindly fix that.
- This is what we should be aiming for: 👇 
in-the-magazine
- This is what we currently have: 👇 
in-the-magazine-clone
## [REQUIRED] - FIX -The featured slideshows section. 
- Let's remove the spacing in the 3 smaller articles on the right-most side in these sections.
featured-clone
- This is what they should look like ([link to page](https://www.newsweek.com/)).
featured

## [REQUIRED] - REMOVE - The scroll that appears during screen breaks.
- During screen breaks, a scroll appears at the bottom of the page that obscures contents. As a result, this is what happens to the view: 👇 
screen-breaks-clone
- This is what is required: 👇 
screen-breaks
- No scroll [link to the page](https://www.newsweek.com/). Kindly fix that. 
## [REQUIRED] - REMOVE - All the inline styling in your markup.
- Remove all the inline styling and move them to the CSS files.
👇 
styling

## [REQUIRED] - VALIDATE - Your markup
- Validate your markup and remove the errors in there. 
validaye
Use this [tool](https://validator.w3.org/nu/#textarea) for that,
## 
Please make these changes and submit another review request.
-
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by JelilFaisalAbudu** [comment]
# Request for Review Per The Changes Required By  TSE Earlier Code Reviews And Feedback#
     All changes have been made and the code is ready for your review again.

**Comment by christianotieno** [comment]
## Pull Request under review by Christian Otieno (TSE)

**Review by christianotieno — APPROVED** [review]
# PROJECT APPROVED :champagne:
Good job. :fireworks: Keep it up.
##
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations on a good job done @JelilFaisalAbudu! :+1:
- Before we proceed with merging, we might want to make sure the live link in the README is working. Be sure to also replace the placeholders in the social links section with your actual username links in the file as well. Make them visible, thanks. I wish you all the very best in your next tasks.
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Comment by JelilFaisalAbudu** [comment]
Project finally approved. Thank you TSEs.

**Pull request merged**
